# Generated by Django 3.2.2 on 2021-05-13 07:09

from django.db import migrations, models
import django_selenium_pdfmaker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Visited URL')),
                ('file', models.FileField(upload_to=django_selenium_pdfmaker.models.file_upload_to, verbose_name='PDF File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
